sonar.projectKey=Smartappli_DEALIoT
sonar.projectName=DEALIoT
sonar.projectVersion=1.0

sonar.sources=airflow,docker-compose.yml,mqtt-kafka-bridge,pipelines,flink,beam,scripts,orchestration,patroni,pgbouncer,apicurio,prometheus,grafana,haproxy,tests
sonar.tests=tests

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/.venv/**,**/__pycache__/**,**/*.pyc,**/.git/**,**/logs/**,**/node_modules/**
sonar.test.inclusions=tests/**/*.py

sonar.python.coverage.reportPaths=coverage.xml
