apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dealiot-secrets
  labels:
    app.kubernetes.io/part-of: dealiot
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: dealiot-secret-store
  target:
    name: dealiot-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: MQTT_PASSWORD
      remoteRef:
        key: dealiot/production/mqtt-password
    - secretKey: KAFKA_SASL_PASSWORD
      remoteRef:
        key: dealiot/production/kafka-sasl-password
    - secretKey: MANAGEMENT_CONSOLE_OIDC_CLIENT_SECRET
      remoteRef:
        key: dealiot/production/management-console-oidc-client-secret
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: dealiot/production/s3-access-key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: dealiot/production/s3-secret-key
    - secretKey: AIRFLOW__CORE__FERNET_KEY
      remoteRef:
        key: dealiot/production/airflow-fernet-key
    - secretKey: AIRFLOW__API__SECRET_KEY
      remoteRef:
        key: dealiot/production/airflow-api-secret-key
    - secretKey: AIRFLOW__API_AUTH__JWT_SECRET
      remoteRef:
        key: dealiot/production/airflow-jwt-secret
    - secretKey: AIRFLOW_ADMIN_PASSWORD
      remoteRef:
        key: dealiot/production/airflow-admin-password
    - secretKey: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
      remoteRef:
        key: dealiot/production/airflow-database-url
    - secretKey: AIRFLOW__CELERY__RESULT_BACKEND
      remoteRef:
        key: dealiot/production/airflow-result-backend
    - secretKey: AIRFLOW__CELERY__BROKER_URL
      remoteRef:
        key: dealiot/production/airflow-broker-url
