"""Generate localized static website pages from the English canonical page."""

from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
WEBSITE_DIR = REPO_ROOT / "website"
BASE_URL = "https://smartappli.io/"
ASSET_VERSION = "20260607-language-dropdown-v2"


LANGUAGES = {
    "bg": {"path": "bg", "og_locale": "bg_BG"},
    "hr": {"path": "hr", "og_locale": "hr_HR"},
    "cs": {"path": "cs", "og_locale": "cs_CZ"},
    "da": {"path": "da", "og_locale": "da_DK"},
    "nl": {"path": "nl", "og_locale": "nl_NL"},
    "et": {"path": "et", "og_locale": "et_EE"},
    "fi": {"path": "fi", "og_locale": "fi_FI"},
    "fr": {"path": "fr", "og_locale": "fr_FR"},
    "de": {"path": "de", "og_locale": "de_DE"},
    "el": {"path": "el", "og_locale": "el_GR"},
    "hu": {"path": "hu", "og_locale": "hu_HU"},
    "ga": {"path": "ga", "og_locale": "ga_IE"},
    "it": {"path": "it", "og_locale": "it_IT"},
    "lv": {"path": "lv", "og_locale": "lv_LV"},
    "lt": {"path": "lt", "og_locale": "lt_LT"},
    "mt": {"path": "mt", "og_locale": "mt_MT"},
    "pl": {"path": "pl", "og_locale": "pl_PL"},
    "pt": {"path": "pt", "og_locale": "pt_PT"},
    "ro": {"path": "ro", "og_locale": "ro_RO"},
    "sk": {"path": "sk", "og_locale": "sk_SK"},
    "sl": {"path": "sl", "og_locale": "sl_SI"},
    "es": {"path": "es", "og_locale": "es_ES"},
    "sv": {"path": "sv", "og_locale": "sv_SE"},
}


ENGLISH = {
    "meta_description": "DEAL presents DEALIoT, DEALHost and DEALData: a production-ready IoT data platform, managed hosting path and data governance layer for scalable field data ecosystems.",
    "keywords": "DEALIoT, DEALHost, DEALData, IoT data platform, Kafka, Flink, Kubernetes, data governance, managed hosting",
    "og_description": "A professional IoT data suite for real-time ingestion, operated infrastructure and governed data sharing.",
    "twitter_description": "Real-time IoT ingestion, operated hosting and governed data products with compliance evidence.",
    "og_image_alt": "DEALIoT, DEALHost and DEALData for scalable IoT data ecosystems.",
    "twitter_image_alt": "DEAL suite public website preview.",
    "website_description": "Public website for the DEAL suite: DEALIoT, DEALHost and DEALData.",
    "app_category": "IoT data platform",
    "dealiot_schema_description": "DEALIoT ingests IoT telemetry and media metadata through MQTT, Kafka, Apicurio, Flink, Beam, Airflow, Prometheus and Grafana.",
    "dealhost_schema_description": "DEALHost is the operated hosting path for DEAL workloads on hardened cloud, hybrid or on-prem infrastructure.",
    "dealhost_schema_service_type": "Managed data platform hosting",
    "dealdata_schema_description": "DEALData structures catalogues, controlled sharing, exports, Data Act evidence, DGA workflows, FAIR publication, Zenodo and OpenAIRE.",
    "dealdata_schema_service_type": "Data governance and sharing",
    "suite_schema_description": "DEAL suite combines IoT ingestion, operated hosting and governed data products.",
    "faq_schema_dealhost": "DEALHost is the hosting and operations path for running DEAL workloads on Kubernetes, cloud, hybrid or on-prem infrastructure.",
    "faq_schema_dealdata": "DEALData is the governance layer for catalogues, controlled sharing, exports and Data Act, DGA and FAIR evidence.",
    "skip": "Skip to content",
    "deal_home": "DEAL home",
    "tagline": "Data ecosystems that scale",
    "primary_nav": "Primary navigation",
    "nav_products": "Products",
    "nav_platform": "Platform",
    "nav_proof": "Proof",
    "nav_adoption": "Adoption",
    "nav_faq": "FAQ",
    "nav_contact": "Contact",
    "choose_language": "Choose language",
    "star": "Star on GitHub",
    "request_demo": "Request a demo",
    "hero_eyebrow": "DEALIoT + DEALHost + DEALData",
    "h1": "Operate field data like a production system.",
    "hero_lede": "DEAL brings DEALIoT, DEALHost and DEALData together for IoT telemetry, operated infrastructure and governed data sharing.",
    "explore_suite": "Explore the suite",
    "see_platform": "See the platform",
    "platform_promises": "Platform promises",
    "coordinated_products": "coordinated products",
    "operations_view": "operations view",
    "compliance_evidence": "compliance evidence",
    "suite_overview": "DEAL suite overview",
    "operate_data_trust": "Operate data with trust",
    "products_eyebrow": "One suite, three adoption paths",
    "build_host_govern": "Build, host and govern.",
    "products_intro": "Each product can be adopted independently. Together, they cover the full cycle from field ingestion to operated infrastructure, governance and controlled data sharing.",
    "dealiot_desc": "Real-time IoT platform for sensors, media metadata and industrial streams. MQTT, Kafka, Flink, Airflow and Kubernetes are assembled to move from prototype to scalable operations.",
    "dealiot_li1": "MQTT to Kafka ingestion",
    "dealiot_li2": "Stream processing and backfill",
    "dealiot_li3": "Integrated observability and DLQ",
    "dealhost_desc": "Operated hosting for critical data workloads: Kubernetes, object storage, monitoring, backups, hardening and continuous operations.",
    "dealhost_li1": "Secured application clusters",
    "dealhost_li2": "Runbooks, alerts and backups",
    "dealhost_li3": "Cloud, hybrid or on-prem paths",
    "dealdata_desc": "Governance and value layer: catalogues, evidence topics, controlled exports, Data Act, DGA, FAIR, Zenodo and OpenAIRE.",
    "dealdata_li1": "Catalogues and data products",
    "dealdata_li2": "Controlled sharing and traceability",
    "dealdata_li3": "Usable compliance evidence",
    "target_platform": "Target platform",
    "open_foundation": "An open foundation that avoids vendor lock-in.",
    "capture": "Capture",
    "capture_desc": "Connected devices, WildFi, MQTT gateways and media producers.",
    "transport": "Transport",
    "transport_desc": "Kafka, schema registry, business topics, DLQ and event contracts.",
    "operate": "Operate",
    "operate_desc": "Kubernetes, DEALHost, observability, security and SLOs.",
    "value": "Value",
    "value_desc": "DEALData, catalogues, exports, compliance evidence and controlled sharing.",
    "why_adopt": "Why adopt",
    "difference": "The difference: an auditable architecture before production.",
    "proof_desc": "The DEAL suite does not only sell a diagram. It provides manifests, tests, workflows, runbooks, security evidence and documentation that reduce adoption risk.",
    "tests": "Tests",
    "ci_guardrails": "CI/CD guardrails",
    "ci_desc": "Unit, integration, deployment, Kustomize, Swarm and supply-chain validation.",
    "scalability": "Scalability",
    "horizontal_design": "Horizontal by design",
    "scale_desc": "Shared MQTT subscriptions, Kafka partitions, Flink task managers, HPA and PDB.",
    "trust": "Trust",
    "dedicated_topics": "Dedicated topics for governance, security, resilience and European obligations.",
    "adoption_path": "Adoption path",
    "public_path": "A public path to evaluate without friction.",
    "adoption_desc": "The DEAL suite exposes a clear path: test locally, scope a 30-day pilot, document integrations and contribute without breaking production guardrails.",
    "evaluate": "Evaluate",
    "reproducible_demo": "Reproducible demo",
    "eval_desc": "Run the smoke test, choose one field stream, measure the first usable event and capture decision evidence.",
    "read_playbook": "Read the pilot playbook",
    "contribute": "Contribute",
    "structured_community": "Structured community",
    "community_desc": "Discussions, feedback forms, support rules, community rituals and roadmap triage make user adoption readable and maintainable.",
    "community_plan": "Community plan",
    "integrate": "Integrate",
    "partners_use_cases": "Partners and use cases",
    "usecase_desc": "Concrete livestock, research, agriculture, industrial, publication and partner scenarios make fit easier to validate.",
    "use_case_catalog": "Use case catalog",
    "direct_answers": "Direct answers",
    "short_answers": "Short answers for fast evaluation.",
    "faq_intro": "This section gives decision-makers, integrators and answer engines the canonical definitions of DEALIoT, DEALHost and DEALData.",
    "q_dealiot": "What is DEALIoT?",
    "a_dealiot": "DEALIoT is a production-oriented IoT data platform for MQTT ingestion, Kafka transport, schema governance, stream processing, backfill and operational evidence.",
    "q_dealhost": "What is DEALHost?",
    "a_dealhost": "DEALHost operates the DEAL suite on hardened infrastructure: Kubernetes, monitoring, backups, runbooks, security and support boundaries.",
    "q_dealdata": "What is DEALData?",
    "a_dealdata": "DEALData structures catalogues, data products, controlled sharing, FAIR exports, Zenodo, OpenAIRE and Data Act or Data Governance Act evidence.",
    "q_eval": "How do I start an evaluation?",
    "a_eval": "The recommended path is to run the local smoke test, choose one representative field stream, scope a 30-day pilot and score the evidence before production.",
    "q_usecases": "Which use cases fit?",
    "a_usecases": "The suite targets research teams, precision agriculture, connected livestock, industrial IoT, public projects and integrators that must industrialize field data.",
    "q_compliance": "Is the platform compliance-certified?",
    "a_compliance": "The repository provides compliance evidence, workflows, topics and templates. These assets support audits, but do not replace organization-specific certification.",
    "start_pilot": "Start a pilot",
    "measurable": "A measurable first use case in 30 days.",
    "launch_desc": "Select a field stream, define value indicators, deploy the pilot chain and measure time to the first usable event.",
    "contact_team": "Contact the team",
    "open_repo": "Open the GitHub repository",
    "deal_ecosystem": "DEAL ecosystem",
    "llms_context": "LLMS context",
}


TRANSLATIONS = {
    "bg": {
        "meta_description": "DEAL представя DEALIoT, DEALHost и DEALData: IoT платформа за данни, управляван хостинг и слой за управление на данни, готови за продукция.",
        "keywords": "DEALIoT, DEALHost, DEALData, IoT платформа за данни, Kafka, Flink, Kubernetes, управление на данни, управляван хостинг",
        "og_description": "Професионален IoT пакет за данни за приемане в реално време, управлявана инфраструктура и контролирано споделяне на данни.",
        "twitter_description": "IoT приемане в реално време, управляван хостинг и контролирани продукти от данни с доказателства за съответствие.",
        "og_image_alt": "DEALIoT, DEALHost и DEALData за мащабируеми IoT екосистеми от данни.",
        "twitter_image_alt": "Преглед на публичния сайт на пакета DEAL.",
        "website_description": "Публичен сайт за пакета DEAL: DEALIoT, DEALHost и DEALData.",
        "app_category": "IoT платформа за данни",
        "dealiot_schema_description": "DEALIoT приема IoT телеметрия и медийни метаданни чрез MQTT, Kafka, Apicurio, Flink, Beam, Airflow, Prometheus и Grafana.",
        "dealhost_schema_description": "DEALHost е управляваният хостинг път за DEAL натоварвания върху подсилена облачна, хибридна или локална инфраструктура.",
        "dealhost_schema_service_type": "Управляван хостинг на платформа за данни",
        "dealdata_schema_description": "DEALData структурира каталози, контролирано споделяне, експорти, доказателства по Data Act, DGA процеси, FAIR публикации, Zenodo и OpenAIRE.",
        "dealdata_schema_service_type": "Управление и споделяне на данни",
        "suite_schema_description": "Пакетът DEAL комбинира IoT приемане, управляван хостинг и контролирани продукти от данни.",
        "faq_schema_dealhost": "DEALHost е пътят за хостинг и операции за DEAL натоварвания върху Kubernetes, облачна, хибридна или локална инфраструктура.",
        "faq_schema_dealdata": "DEALData е слой за управление на каталози, контролирано споделяне, експорти и доказателства по Data Act, DGA и FAIR.",
        "skip": "Към съдържанието",
        "deal_home": "Начало DEAL",
        "tagline": "Екосистеми от данни, които се мащабират",
        "primary_nav": "Основна навигация",
        "nav_products": "Продукти",
        "nav_platform": "Платформа",
        "nav_proof": "Доказателства",
        "nav_adoption": "Внедряване",
        "nav_faq": "Въпроси",
        "nav_contact": "Контакт",
        "choose_language": "Изберете език",
        "star": "Звезда в GitHub",
        "request_demo": "Заявете демо",
        "hero_eyebrow": "DEALIoT + DEALHost + DEALData",
        "h1": "Управлявайте теренните данни като продукционна система.",
        "hero_lede": "DEAL обединява DEALIoT, DEALHost и DEALData за IoT телеметрия, управлявана инфраструктура и контролирано споделяне на данни.",
        "explore_suite": "Разгледайте пакета",
        "see_platform": "Вижте платформата",
        "platform_promises": "Обещания на платформата",
        "coordinated_products": "координирани продукта",
        "operations_view": "оперативен изглед",
        "compliance_evidence": "доказателства за съответствие",
        "suite_overview": "Преглед на пакета DEAL",
        "operate_data_trust": "Управлявайте данни с доверие",
        "products_eyebrow": "Един пакет, три пътя за внедряване",
        "build_host_govern": "Създавайте, хоствайте и управлявайте.",
        "products_intro": "Всеки продукт може да се внедрява самостоятелно. Заедно покриват целия цикъл от теренно приемане до управлявана инфраструктура, управление и контролирано споделяне на данни.",
        "dealiot_desc": "IoT платформа в реално време за сензори, медийни метаданни и индустриални потоци. MQTT, Kafka, Flink, Airflow и Kubernetes са сглобени за преход от прототип към мащабируеми операции.",
        "dealiot_li1": "Приемане от MQTT към Kafka",
        "dealiot_li2": "Поточна обработка и backfill",
        "dealiot_li3": "Интегрирана наблюдаемост и DLQ",
        "dealhost_desc": "Управляван хостинг за критични data натоварвания: Kubernetes, обектно съхранение, мониторинг, резервни копия, подсилване и непрекъснати операции.",
        "dealhost_li1": "Защитени приложни клъстери",
        "dealhost_li2": "Runbooks, аларми и резервни копия",
        "dealhost_li3": "Облачни, хибридни или локални пътища",
        "dealdata_desc": "Слой за управление и стойност: каталози, evidence topics, контролирани експорти, Data Act, DGA, FAIR, Zenodo и OpenAIRE.",
        "dealdata_li1": "Каталози и продукти от данни",
        "dealdata_li2": "Контролирано споделяне и проследимост",
        "dealdata_li3": "Използваеми доказателства за съответствие",
        "target_platform": "Целева платформа",
        "open_foundation": "Отворена основа, която избягва vendor lock-in.",
        "capture": "Заснемане",
        "capture_desc": "Свързани устройства, WildFi, MQTT шлюзове и медийни производители.",
        "transport": "Транспорт",
        "transport_desc": "Kafka, schema registry, бизнес topics, DLQ и договори за събития.",
        "operate": "Операции",
        "operate_desc": "Kubernetes, DEALHost, наблюдаемост, сигурност и SLO.",
        "value": "Стойност",
        "value_desc": "DEALData, каталози, експорти, доказателства за съответствие и контролирано споделяне.",
        "why_adopt": "Защо да внедрите",
        "difference": "Разликата: одитируема архитектура преди продукция.",
        "proof_desc": "Пакетът DEAL не продава само диаграма. Той предоставя манифести, тестове, workflows, runbooks, доказателства за сигурност и документация, които намаляват риска от внедряване.",
        "tests": "Тестове",
        "ci_guardrails": "CI/CD предпазни механизми",
        "ci_desc": "Валидация на unit, integration, deployment, Kustomize, Swarm и supply chain.",
        "scalability": "Мащабируемост",
        "horizontal_design": "Хоризонтално по дизайн",
        "scale_desc": "Shared MQTT subscriptions, Kafka partitions, Flink task managers, HPA и PDB.",
        "trust": "Доверие",
        "dedicated_topics": "Специални topics за управление, сигурност, устойчивост и европейски задължения.",
        "adoption_path": "Път за внедряване",
        "public_path": "Публичен път за оценка без триене.",
        "adoption_desc": "Пакетът DEAL показва ясен път: тествайте локално, дефинирайте 30-дневен пилот, документирайте интеграции и допринасяйте без да нарушавате production guardrails.",
        "evaluate": "Оценете",
        "reproducible_demo": "Възпроизводимо демо",
        "eval_desc": "Стартирайте smoke test, изберете един теренен поток, измерете първото използваемо събитие и съберете доказателства за решение.",
        "read_playbook": "Прочетете pilot playbook",
        "contribute": "Допринесете",
        "structured_community": "Структурирана общност",
        "community_desc": "Discussions, формуляри за feedback, правила за support, общностни ритуали и roadmap triage правят внедряването четимо и поддържано.",
        "community_plan": "План за общността",
        "integrate": "Интегрирайте",
        "partners_use_cases": "Партньори и случаи на употреба",
        "usecase_desc": "Конкретни сценарии за животновъдство, изследвания, земеделие, индустрия, публикации и партньори улесняват валидирането на fit.",
        "use_case_catalog": "Каталог на случаи на употреба",
        "direct_answers": "Директни отговори",
        "short_answers": "Кратки отговори за бърза оценка.",
        "faq_intro": "Този раздел дава на decision-makers, интегратори и answer engines каноничните дефиниции на DEALIoT, DEALHost и DEALData.",
        "q_dealiot": "Какво е DEALIoT?",
        "a_dealiot": "DEALIoT е IoT платформа за данни, ориентирана към продукция, за MQTT приемане, Kafka транспорт, schema governance, stream processing, backfill и оперативни доказателства.",
        "q_dealhost": "Какво е DEALHost?",
        "a_dealhost": "DEALHost изпълнява пакета DEAL върху подсилена инфраструктура: Kubernetes, мониторинг, резервни копия, runbooks, сигурност и граници на support.",
        "q_dealdata": "Какво е DEALData?",
        "a_dealdata": "DEALData структурира каталози, продукти от данни, контролирано споделяне, FAIR експорти, Zenodo, OpenAIRE и доказателства по Data Act или Data Governance Act.",
        "q_eval": "Как да започна оценка?",
        "a_eval": "Препоръчаният път е да стартирате локалния smoke test, да изберете представителен теренен поток, да дефинирате 30-дневен пилот и да оцените доказателствата преди продукция.",
        "q_usecases": "Кои случаи на употреба пасват?",
        "a_usecases": "Пакетът е насочен към изследователски екипи, прецизно земеделие, свързано животновъдство, индустриален IoT, публични проекти и интегратори, които трябва да индустриализират теренни данни.",
        "q_compliance": "Платформата сертифицирана ли е за съответствие?",
        "a_compliance": "Repository предоставя доказателства за съответствие, workflows, topics и templates. Тези активи подпомагат одити, но не заменят специфична за организацията сертификация.",
        "start_pilot": "Започнете пилот",
        "measurable": "Първи измерим use case за 30 дни.",
        "launch_desc": "Изберете теренен поток, дефинирайте индикатори за стойност, внедрете пилотната верига и измерете времето до първото използваемо събитие.",
        "contact_team": "Свържете се с екипа",
        "open_repo": "Отворете GitHub repository",
        "deal_ecosystem": "Екосистема DEAL",
        "llms_context": "LLMS контекст",
    },
    "hr": {
        "meta_description": "DEAL predstavlja DEALIoT, DEALHost i DEALData: produkcijski spremnu IoT podatkovnu platformu, put upravljanog hostinga i sloj upravljanja podacima.",
        "keywords": "DEALIoT, DEALHost, DEALData, IoT podatkovna platforma, Kafka, Flink, Kubernetes, upravljanje podacima, upravljani hosting",
        "og_description": "Profesionalni IoT podatkovni paket za unos u stvarnom vremenu, upravljanu infrastrukturu i kontrolirano dijeljenje podataka.",
        "twitter_description": "IoT unos u stvarnom vremenu, upravljani hosting i uređeni podatkovni proizvodi s dokazima usklađenosti.",
        "og_image_alt": "DEALIoT, DEALHost i DEALData za skalabilne IoT podatkovne ekosustave.",
        "twitter_image_alt": "Pregled javne stranice paketa DEAL.",
        "website_description": "Javna stranica za paket DEAL: DEALIoT, DEALHost i DEALData.",
        "app_category": "IoT podatkovna platforma",
        "dealiot_schema_description": "DEALIoT prima IoT telemetriju i medijske metapodatke kroz MQTT, Kafka, Apicurio, Flink, Beam, Airflow, Prometheus i Grafana.",
        "dealhost_schema_description": "DEALHost je upravljani hosting put za DEAL opterećenja na ojačanoj cloud, hibridnoj ili on-prem infrastrukturi.",
        "dealhost_schema_service_type": "Upravljani hosting podatkovne platforme",
        "dealdata_schema_description": "DEALData strukturira kataloge, kontrolirano dijeljenje, izvoze, Data Act dokaze, DGA procese, FAIR objavu, Zenodo i OpenAIRE.",
        "dealdata_schema_service_type": "Upravljanje i dijeljenje podataka",
        "suite_schema_description": "Paket DEAL spaja IoT unos, upravljani hosting i uređene podatkovne proizvode.",
        "faq_schema_dealhost": "DEALHost je put hostinga i operacija za DEAL opterećenja na Kubernetesu, cloudu, hibridnoj ili on-prem infrastrukturi.",
        "faq_schema_dealdata": "DEALData je sloj upravljanja za kataloge, kontrolirano dijeljenje, izvoze i Data Act, DGA i FAIR dokaze.",
        "skip": "Preskoči na sadržaj",
        "deal_home": "DEAL početna",
        "tagline": "Podatkovni ekosustavi koji se skaliraju",
        "primary_nav": "Glavna navigacija",
        "nav_products": "Proizvodi",
        "nav_platform": "Platforma",
        "nav_proof": "Dokazi",
        "nav_adoption": "Usvajanje",
        "nav_faq": "ČPP",
        "nav_contact": "Kontakt",
        "choose_language": "Odaberite jezik",
        "star": "Označi zvjezdicom na GitHubu",
        "request_demo": "Zatraži demo",
        "hero_eyebrow": "DEALIoT + DEALHost + DEALData",
        "h1": "Upravljajte terenskim podacima kao produkcijskim sustavom.",
        "hero_lede": "DEAL povezuje DEALIoT, DEALHost i DEALData za IoT telemetriju, upravljanu infrastrukturu i uređeno dijeljenje podataka.",
        "explore_suite": "Istražite paket",
        "see_platform": "Pogledajte platformu",
        "platform_promises": "Obećanja platforme",
        "coordinated_products": "usklađena proizvoda",
        "operations_view": "operativni prikaz",
        "compliance_evidence": "dokazi usklađenosti",
        "suite_overview": "Pregled paketa DEAL",
        "operate_data_trust": "Upravljajte podacima s povjerenjem",
        "products_eyebrow": "Jedan paket, tri puta usvajanja",
        "build_host_govern": "Gradite, hostajte i upravljajte.",
        "products_intro": "Svaki proizvod može se usvojiti zasebno. Zajedno pokrivaju cijeli ciklus od terenskog unosa do upravljane infrastrukture, governancea i kontroliranog dijeljenja podataka.",
        "dealiot_desc": "IoT platforma u stvarnom vremenu za senzore, medijske metapodatke i industrijske tokove. MQTT, Kafka, Flink, Airflow i Kubernetes povezani su za prijelaz od prototipa do skalabilnih operacija.",
        "dealiot_li1": "Unos iz MQTT-a u Kafku",
        "dealiot_li2": "Stream obrada i backfill",
        "dealiot_li3": "Integrirana observabilnost i DLQ",
        "dealhost_desc": "Upravljani hosting za kritična podatkovna opterećenja: Kubernetes, objektna pohrana, monitoring, sigurnosne kopije, očvršćivanje i kontinuirane operacije.",
        "dealhost_li1": "Osigurani aplikacijski klasteri",
        "dealhost_li2": "Runbookovi, upozorenja i backupi",
        "dealhost_li3": "Cloud, hibridni ili on-prem putevi",
        "dealdata_desc": "Sloj upravljanja i vrijednosti: katalozi, evidence topics, kontrolirani izvozi, Data Act, DGA, FAIR, Zenodo i OpenAIRE.",
        "dealdata_li1": "Katalozi i podatkovni proizvodi",
        "dealdata_li2": "Kontrolirano dijeljenje i sljedivost",
        "dealdata_li3": "Upotrebljivi dokazi usklađenosti",
        "target_platform": "Ciljna platforma",
        "open_foundation": "Otvorena osnova koja izbjegava vendor lock-in.",
        "capture": "Prikupljanje",
        "capture_desc": "Povezani uređaji, WildFi, MQTT gatewayi i medijski proizvođači.",
        "transport": "Prijenos",
        "transport_desc": "Kafka, schema registry, poslovni topics, DLQ i ugovori događaja.",
        "operate": "Operacije",
        "operate_desc": "Kubernetes, DEALHost, observabilnost, sigurnost i SLO.",
        "value": "Vrijednost",
        "value_desc": "DEALData, katalozi, izvozi, dokazi usklađenosti i kontrolirano dijeljenje.",
        "why_adopt": "Zašto usvojiti",
        "difference": "Razlika: auditabilna arhitektura prije produkcije.",
        "proof_desc": "Paket DEAL ne prodaje samo dijagram. Pruža manifeste, testove, workflows, runbookove, sigurnosne dokaze i dokumentaciju koji smanjuju rizik usvajanja.",
        "tests": "Testovi",
        "ci_guardrails": "CI/CD zaštitne mjere",
        "ci_desc": "Validacija unit, integration, deployment, Kustomize, Swarm i supply chain.",
        "scalability": "Skalabilnost",
        "horizontal_design": "Horizontalno po dizajnu",
        "scale_desc": "Shared MQTT subscriptions, Kafka partitions, Flink task managers, HPA i PDB.",
        "trust": "Povjerenje",
        "dedicated_topics": "Namjenski topics za governance, sigurnost, otpornost i europske obveze.",
        "adoption_path": "Put usvajanja",
        "public_path": "Javni put za evaluaciju bez trenja.",
        "adoption_desc": "Paket DEAL nudi jasan put: testirajte lokalno, odredite 30-dnevni pilot, dokumentirajte integracije i doprinosite bez narušavanja production guardrails.",
        "evaluate": "Evaluirajte",
        "reproducible_demo": "Reproducibilni demo",
        "eval_desc": "Pokrenite smoke test, odaberite jedan terenski tok, izmjerite prvi upotrebljivi događaj i zabilježite dokaze odluke.",
        "read_playbook": "Pročitajte pilot playbook",
        "contribute": "Doprinesite",
        "structured_community": "Strukturirana zajednica",
        "community_desc": "Discussions, feedback obrasci, pravila podrške, rituali zajednice i roadmap triage čine usvajanje čitljivim i održivim.",
        "community_plan": "Plan zajednice",
        "integrate": "Integrirajte",
        "partners_use_cases": "Partneri i slučajevi uporabe",
        "usecase_desc": "Konkretni scenariji za stočarstvo, istraživanje, poljoprivredu, industriju, objavu i partnere olakšavaju validaciju fita.",
        "use_case_catalog": "Katalog slučajeva uporabe",
        "direct_answers": "Izravni odgovori",
        "short_answers": "Kratki odgovori za brzu evaluaciju.",
        "faq_intro": "Ovaj odjeljak daje decision-makerima, integratorima i answer engines kanonske definicije DEALIoT, DEALHost i DEALData.",
        "q_dealiot": "Što je DEALIoT?",
        "a_dealiot": "DEALIoT je produkcijski orijentirana IoT podatkovna platforma za MQTT unos, Kafka prijenos, schema governance, stream processing, backfill i operativne dokaze.",
        "q_dealhost": "Što je DEALHost?",
        "a_dealhost": "DEALHost pokreće paket DEAL na ojačanoj infrastrukturi: Kubernetes, monitoring, backupi, runbookovi, sigurnost i granice podrške.",
        "q_dealdata": "Što je DEALData?",
        "a_dealdata": "DEALData strukturira kataloge, podatkovne proizvode, kontrolirano dijeljenje, FAIR izvoze, Zenodo, OpenAIRE i Data Act ili Data Governance Act dokaze.",
        "q_eval": "Kako započeti evaluaciju?",
        "a_eval": "Preporučeni put je pokrenuti lokalni smoke test, odabrati reprezentativni terenski tok, definirati 30-dnevni pilot i ocijeniti dokaze prije produkcije.",
        "q_usecases": "Koji slučajevi uporabe odgovaraju?",
        "a_usecases": "Paket cilja istraživačke timove, preciznu poljoprivredu, povezano stočarstvo, industrijski IoT, javne projekte i integratore koji moraju industrijalizirati terenske podatke.",
        "q_compliance": "Je li platforma certificirana za usklađenost?",
        "a_compliance": "Repository pruža dokaze usklađenosti, workflows, topics i templates. Ti artefakti podržavaju audite, ali ne zamjenjuju certifikaciju specifičnu za organizaciju.",
        "start_pilot": "Pokrenite pilot",
        "measurable": "Prvi mjerljiv use case u 30 dana.",
        "launch_desc": "Odaberite terenski tok, definirajte pokazatelje vrijednosti, implementirajte pilot lanac i izmjerite vrijeme do prvog upotrebljivog događaja.",
        "contact_team": "Kontaktirajte tim",
        "open_repo": "Otvorite GitHub repository",
        "deal_ecosystem": "DEAL ekosustav",
        "llms_context": "LLMS kontekst",
    },
}


def complete_translations() -> None:
    """Extend TRANSLATIONS with compact entries kept outside the initial patch block."""
    TRANSLATIONS.update(_additional_translations())


def _additional_translations() -> dict[str, dict[str, str]]:
    return {
        "cs": {
            "meta_description": "DEAL představuje DEALIoT, DEALHost a DEALData: produkčně připravenou IoT datovou platformu, řízený hosting a vrstvu správy dat.",
            "keywords": "DEALIoT, DEALHost, DEALData, IoT datová platforma, Kafka, Flink, Kubernetes, správa dat, řízený hosting",
            "og_description": "Profesionální IoT datový balík pro příjem v reálném čase, provozovanou infrastrukturu a řízené sdílení dat.",
            "twitter_description": "IoT příjem v reálném čase, provozovaný hosting a řízené datové produkty s důkazy souladu.",
            "og_image_alt": "DEALIoT, DEALHost a DEALData pro škálovatelné IoT datové ekosystémy.",
            "twitter_image_alt": "Náhled veřejného webu balíku DEAL.",
            "website_description": "Veřejný web pro balík DEAL: DEALIoT, DEALHost a DEALData.",
            "app_category": "IoT datová platforma",
            "dealiot_schema_description": "DEALIoT přijímá IoT telemetrii a mediální metadata přes MQTT, Kafka, Apicurio, Flink, Beam, Airflow, Prometheus a Grafana.",
            "dealhost_schema_description": "DEALHost je provozovaná hostingová cesta pro DEAL zátěže na odolné cloudové, hybridní nebo on-prem infrastruktuře.",
            "dealhost_schema_service_type": "Řízený hosting datové platformy",
            "dealdata_schema_description": "DEALData strukturuje katalogy, řízené sdílení, exporty, důkazy Data Act, DGA workflow, FAIR publikování, Zenodo a OpenAIRE.",
            "dealdata_schema_service_type": "Správa a sdílení dat",
            "suite_schema_description": "Balík DEAL kombinuje IoT příjem, provozovaný hosting a řízené datové produkty.",
            "faq_schema_dealhost": "DEALHost je cesta hostingu a provozu pro DEAL zátěže na Kubernetes, cloudové, hybridní nebo on-prem infrastruktuře.",
            "faq_schema_dealdata": "DEALData je vrstva správy pro katalogy, řízené sdílení, exporty a důkazy Data Act, DGA a FAIR.",
            "skip": "Přejít na obsah",
            "deal_home": "Domů DEAL",
            "tagline": "Datové ekosystémy, které škálují",
            "primary_nav": "Hlavní navigace",
            "nav_products": "Produkty",
            "nav_platform": "Platforma",
            "nav_proof": "Důkazy",
            "nav_adoption": "Adopce",
            "nav_faq": "FAQ",
            "nav_contact": "Kontakt",
            "choose_language": "Vyberte jazyk",
            "star": "Přidat hvězdu na GitHubu",
            "request_demo": "Vyžádat demo",
            "hero_eyebrow": "DEALIoT + DEALHost + DEALData",
            "h1": "Provozujte terénní data jako produkční systém.",
            "hero_lede": "DEAL propojuje DEALIoT, DEALHost a DEALData pro IoT telemetrii, provozovanou infrastrukturu a řízené sdílení dat.",
            "explore_suite": "Prozkoumat balík",
            "see_platform": "Zobrazit platformu",
            "platform_promises": "Přísliby platformy",
            "coordinated_products": "koordinované produkty",
            "operations_view": "provozní přehled",
            "compliance_evidence": "důkazy souladu",
            "suite_overview": "Přehled balíku DEAL",
            "operate_data_trust": "Provozujte data s důvěrou",
            "products_eyebrow": "Jeden balík, tři cesty adopce",
            "build_host_govern": "Budujte, hostujte a spravujte.",
            "products_intro": "Každý produkt lze přijmout samostatně. Společně pokrývají celý cyklus od terénního příjmu přes provozovanou infrastrukturu až po správu a řízené sdílení dat.",
            "dealiot_desc": "IoT platforma v reálném čase pro senzory, mediální metadata a průmyslové streamy. MQTT, Kafka, Flink, Airflow a Kubernetes jsou sestaveny pro přechod od prototypu ke škálovatelnému provozu.",
            "dealiot_li1": "Příjem z MQTT do Kafka",
            "dealiot_li2": "Streamové zpracování a backfill",
            "dealiot_li3": "Integrovaná observabilita a DLQ",
            "dealhost_desc": "Provozovaný hosting pro kritické datové zátěže: Kubernetes, objektové úložiště, monitoring, zálohy, hardening a nepřetržitý provoz.",
            "dealhost_li1": "Zabezpečené aplikační clustery",
            "dealhost_li2": "Runbooky, alerty a zálohy",
            "dealhost_li3": "Cloudové, hybridní nebo on-prem cesty",
            "dealdata_desc": "Vrstva správy a hodnoty: katalogy, evidence topics, řízené exporty, Data Act, DGA, FAIR, Zenodo a OpenAIRE.",
            "dealdata_li1": "Katalogy a datové produkty",
            "dealdata_li2": "Řízené sdílení a sledovatelnost",
            "dealdata_li3": "Použitelné důkazy souladu",
            "target_platform": "Cílová platforma",
            "open_foundation": "Otevřený základ, který se vyhýbá vendor lock-in.",
            "capture": "Sběr",
            "capture_desc": "Připojená zařízení, WildFi, MQTT brány a mediální producenti.",
            "transport": "Přenos",
            "transport_desc": "Kafka, schema registry, business topics, DLQ a kontrakty událostí.",
            "operate": "Provoz",
            "operate_desc": "Kubernetes, DEALHost, observabilita, bezpečnost a SLO.",
            "value": "Hodnota",
            "value_desc": "DEALData, katalogy, exporty, důkazy souladu a řízené sdílení.",
            "why_adopt": "Proč adoptovat",
            "difference": "Rozdíl: auditovatelná architektura před produkcí.",
            "proof_desc": "Balík DEAL neprodává jen diagram. Poskytuje manifesty, testy, workflow, runbooky, bezpečnostní důkazy a dokumentaci, které snižují riziko adopce.",
            "tests": "Testy",
            "ci_guardrails": "CI/CD mantinely",
            "ci_desc": "Validace unit, integration, deployment, Kustomize, Swarm a supply chain.",
            "scalability": "Škálovatelnost",
            "horizontal_design": "Horizontálně už návrhem",
            "scale_desc": "Shared MQTT subscriptions, Kafka partitions, Flink task managers, HPA a PDB.",
            "trust": "Důvěra",
            "dedicated_topics": "Vyhrazené topics pro governance, bezpečnost, odolnost a evropské povinnosti.",
            "adoption_path": "Cesta adopce",
            "public_path": "Veřejná cesta k hodnocení bez tření.",
            "adoption_desc": "Balík DEAL ukazuje jasnou cestu: testujte lokálně, vymezte 30denní pilot, dokumentujte integrace a přispívejte bez porušení production guardrails.",
            "evaluate": "Vyhodnotit",
            "reproducible_demo": "Reprodukovatelné demo",
            "eval_desc": "Spusťte smoke test, vyberte jeden terénní stream, změřte první použitelnou událost a zachyťte rozhodovací důkazy.",
            "read_playbook": "Přečíst pilotní playbook",
            "contribute": "Přispět",
            "structured_community": "Strukturovaná komunita",
            "community_desc": "Discussions, feedback formuláře, pravidla podpory, komunitní rituály a roadmap triage dělají adopci čitelnou a udržovatelnou.",
            "community_plan": "Plán komunity",
            "integrate": "Integrovat",
            "partners_use_cases": "Partneři a případy použití",
            "usecase_desc": "Konkrétní scénáře pro chov, výzkum, zemědělství, průmysl, publikace a partnery usnadňují ověření fitu.",
            "use_case_catalog": "Katalog případů použití",
            "direct_answers": "Přímé odpovědi",
            "short_answers": "Krátké odpovědi pro rychlé hodnocení.",
            "faq_intro": "Tato sekce dává decision-makerům, integrátorům a answer engines kanonické definice DEALIoT, DEALHost a DEALData.",
            "q_dealiot": "Co je DEALIoT?",
            "a_dealiot": "DEALIoT je produkčně orientovaná IoT datová platforma pro MQTT příjem, Kafka transport, schema governance, stream processing, backfill a provozní důkazy.",
            "q_dealhost": "Co je DEALHost?",
            "a_dealhost": "DEALHost provozuje balík DEAL na odolné infrastruktuře: Kubernetes, monitoring, zálohy, runbooky, bezpečnost a hranice podpory.",
            "q_dealdata": "Co je DEALData?",
            "a_dealdata": "DEALData strukturuje katalogy, datové produkty, řízené sdílení, FAIR exporty, Zenodo, OpenAIRE a důkazy Data Act nebo Data Governance Act.",
            "q_eval": "Jak začít hodnocení?",
            "a_eval": "Doporučená cesta je spustit lokální smoke test, vybrat reprezentativní terénní stream, vymezit 30denní pilot a vyhodnotit důkazy před produkcí.",
            "q_usecases": "Které případy použití sedí?",
            "a_usecases": "Balík cílí na výzkumné týmy, precizní zemědělství, propojený chov, průmyslové IoT, veřejné projekty a integrátory, kteří musí industrializovat terénní data.",
            "q_compliance": "Je platforma certifikována pro compliance?",
            "a_compliance": "Repository poskytuje důkazy souladu, workflow, topics a templates. Tyto artefakty podporují audity, ale nenahrazují certifikaci specifickou pro organizaci.",
            "start_pilot": "Spustit pilot",
            "measurable": "První měřitelný use case za 30 dní.",
            "launch_desc": "Vyberte terénní stream, definujte ukazatele hodnoty, nasaďte pilotní řetězec a změřte čas k první použitelné události.",
            "contact_team": "Kontaktovat tým",
            "open_repo": "Otevřít GitHub repository",
            "deal_ecosystem": "Ekosystém DEAL",
            "llms_context": "LLMS kontext",
        },
    }


def localized_url(path: str) -> str:
    return f"{BASE_URL}{path}/"


def apply_translations(html: str, lang: str, copy: dict[str, str]) -> str:
    replacements = {ENGLISH[key]: value for key, value in copy.items() if key in ENGLISH}
    for source, target in sorted(replacements.items(), key=lambda item: len(item[0]), reverse=True):
        html = html.replace(source, target)

    config = LANGUAGES[lang]
    path = config["path"]
    url = localized_url(path)

    html = html.replace('<html lang="en-US">', f'<html lang="{lang}">')
    html = html.replace('<link rel="canonical" href="https://smartappli.io/">', f'<link rel="canonical" href="{url}">')
    html = html.replace('<meta property="og:url" content="https://smartappli.io/">', f'<meta property="og:url" content="{url}">')
    html = html.replace('<meta property="og:locale" content="en_US">', f'<meta property="og:locale" content="{config["og_locale"]}">')
    html = html.replace('<meta property="og:locale:alternate" content="fr_FR">', '<meta property="og:locale:alternate" content="en_US">')
    html = html.replace('"inLanguage": "en-US"', f'"inLanguage": "{lang}"')

    html = html.replace('href="assets/', 'href="../assets/')
    html = html.replace('href="site.webmanifest"', 'href="../site.webmanifest"')
    html = html.replace('href="humans.txt"', 'href="../humans.txt"')
    html = html.replace(f'href="styles.css?v={ASSET_VERSION}"', f'href="../styles.css?v={ASSET_VERSION}"')
    html = html.replace(f'src="app.js?v={ASSET_VERSION}"', f'src="../app.js?v={ASSET_VERSION}"')

    html = html.replace('<option value="https://smartappli.io/" lang="en-US" selected>', '<option value="https://smartappli.io/" lang="en-US">')
    html = html.replace(f'<option value="{url}" lang="{lang}">', f'<option value="{url}" lang="{lang}" selected>')
    html = html.replace(
        '<span><a href="https://smartappli.io/fr/" hreflang="fr" lang="fr">Français</a> / <a href="https://smartappli.io/llms.txt">LLMS context</a></span>',
        f'<span><a href="https://smartappli.io/" hreflang="en-US" lang="en-US">English</a> / <a href="https://smartappli.io/llms.txt">{copy["llms_context"]}</a></span>',
    )
    return html


def main() -> None:
    complete_translations()
    missing_languages = set(LANGUAGES) - set(TRANSLATIONS)
    if missing_languages:
        raise SystemExit(f"Missing translations: {sorted(missing_languages)}")

    template = (WEBSITE_DIR / "index.html").read_text(encoding="utf-8")
    for lang, config in LANGUAGES.items():
        copy = TRANSLATIONS[lang]
        missing_keys = set(ENGLISH) - set(copy)
        if missing_keys:
            raise SystemExit(f"{lang} missing keys: {sorted(missing_keys)}")
        output = apply_translations(template, lang, copy)
        target_dir = WEBSITE_DIR / config["path"]
        target_dir.mkdir(parents=True, exist_ok=True)
        (target_dir / "index.html").write_text(output, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
