rootLogger.level = INFO
rootLogger.appenderRef.console.ref = ConsoleAppender

appender.console.name = ConsoleAppender
appender.console.type = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n

logger.kafka.name = org.apache.kafka
logger.kafka.level = WARN

logger.kafkaShaded.name = org.apache.flink.kafka.shaded.org.apache.kafka
logger.kafkaShaded.level = WARN

logger.flinkKafka.name = org.apache.flink.connector.kafka
logger.flinkKafka.level = WARN
