name: OSV-Scanner

on:
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]
  schedule:
    - cron: '33 22 * * 3'
  push:
    branches: ["main"]

permissions:
  security-events: write
  contents: read

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run OSV scan (SARIF)
        run: |
          docker run --rm \
            -v "$PWD:/repo" \
            -w /repo \
            ghcr.io/google/osv-scanner:v2 \
            scan -r --skip-git --format sarif --output results.sarif ./

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif

  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run OSV scan (SARIF)
        run: |
          docker run --rm \
            -v "$PWD:/repo" \
            -w /repo \
            ghcr.io/google/osv-scanner:v2 \
            scan -r --skip-git --format sarif --output results.sarif ./

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
